(() => {
'use strict';
const chart=window.PullCharts;if(!chart)return;
const annotation='<p class="data-annotation">Illustrative data only. Production collection: authorized social insights and dated account exports for audience; GA4 or owner exports for qualified visits; reviewed source corpus for press. Estimated analyst effort: 1–2 hours per source per reporting window at an assumed $50/hour, excluding provider fees. A shared index allows relative comparison, not combined reach or causal attribution.</p>';
const trend=chart.figure({type:'line',title:'Relative growth from launch',unit:'%',labels:['Launch','Day 7','Day 14','Day 21','Day 30'],series:[{name:'BRUT audience · demo',values:[0,2.1,4.8,7,8.4]},{name:'Starting level',values:[0,0,0,0,0]}],note:'Simulated intermediate observations. Percentage change from launch audience. Not measured campaign performance.'});
const press=chart.figure({type:'bar',title:'Press coverage by week',unit:'placements',labels:['Week 1','Week 2','Week 3','Week 4'],series:[{name:'Qualified placements · demo',values:[12,7,5,3]}],note:'Illustrative distribution of the existing 27-placement example. Not collected weekly observations.'});
for(const root of document.querySelectorAll('[data-analytics-visuals]')){
 if(root.dataset.analyticsVisuals==='overview')root.innerHTML=`<section class="data-spread"><p class="section-label">Illustrative 30-day read · BRUT × FAUX</p><h2>What changed. How much. Against what.</h2><p>Read growth against a starting point, then examine the source. These charts demonstrate the reporting format; they are not live campaign results.</p><div class="data-spread-grid"><div><div class="data-big">+8.4% <small>BRUT audience since launch</small></div>${trend}<p class="data-explanation">The audience ended above its starting level. Without a comparison group, this does not isolate the partnership’s contribution.</p></div><div><div class="data-big">27 <small>qualified press placements · demo</small></div>${press}<p class="data-explanation">Timing helps distinguish the launch spike from sustained coverage. Counts alone do not establish customer demand.</p></div></div>${annotation}</section>`;
 else root.innerHTML=`<section class="data-spread"><p class="section-label">Change, in context · illustrative</p><h2>Compare like with like.</h2><p>Each chart has its own denominator. Audience compares launch and end snapshots; visits compare equal-length periods.</p><div class="data-spread-grid"><div><div class="data-big">+8.4% <small>audience change</small></div>${chart.compare('BRUT audience index','index',100,108.4,'Baseline = audience at launch; result = audience at day 30. Illustrative.')}</div><div><div class="data-big">+18% <small>qualified visits</small></div>${chart.compare('Qualified visits index','index',100,118,'Baseline = previous equal-length period. Illustrative.')}</div></div>${annotation}<p class="data-explanation">Positive sentiment is 74% in the existing demo. A prior comparable sample is missing, so sentiment change is not shown.</p></section>`;
}
})();
