(() => {
'use strict';
const KEY='the-pull:campaign-plan:v1', kit=window.PULL_CAMPAIGN_KIT;
const roots=[...document.querySelectorAll('[data-campaign-planner]')];if(!kit||!roots.length)return;
let plan={concept:'The Ritual · a shared hospitality experience and take-home object',benefit:'Give guests a distinctive experience they can use, remember and take home.',approvedA:false,approvedB:false,reserve:10,assetsA:'',assetsB:'',items:structuredClone(kit.items)};
try{const p=JSON.parse(localStorage.getItem(KEY)||'null');if(p&&Array.isArray(p.items)&&p.items.length)plan={...plan,...p}}catch{}
let active='DI03',view='activities',stage='all',filter='selected',message='Prototype · changes save in this browser, not to partner accounts.';
const money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(n);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const safe=s=>{try{return ['https:','http:'].includes(new URL(s).protocol)}catch{return false}};
const link=(url,label)=>safe(url)?`<a href="${esc(url)}" target="_blank" rel="noopener">${label} ↗</a>`:`<span class="muted">${label}: not linked</span>`;
const cost=i=>i.included?Number(i.price)*Number(i.quantity):0;
const external=i=>!['Agency fee','Brand contribution'].includes(i.category);
function totals(){return plan.items.reduce((a,i)=>{const c=cost(i),r=external(i)?c*plan.reserve/100:0;a.base+=c;a.reserve+=r;a.a+=(c+r)*i.share/100;a.b+=(c+r)*(1-i.share/100);a.total+=c+r;a.categories[i.category]=(a.categories[i.category]||0)+c;return a},{base:0,reserve:0,a:0,b:0,total:0,categories:{}})}
function save(){try{localStorage.setItem(KEY,JSON.stringify(plan));message='Saved in this browser. Export a copy to share with partners.'}catch{message='Browser storage unavailable. Export your plan before leaving.'}}
const statuses=['Not started','In progress','Needs review','Ready','Live','Complete'];
function detail(){const i=plan.items.find(i=>i.id===active);if(!i)return '';const g=kit.guides.find(g=>g.ids.split(/\s*\+\s*/).includes(i.id));return `<section class="plan-detail" aria-label="Activity detail"><div class="plan-detail-title"><div><p class="section-label">${i.id} · ${i.stage}</p><h3>${esc(i.title)}</h3></div><span class="pill">${i.included?'In plan':'Optional · excluded from totals'}</span></div><p>${esc(i.deliverables)}</p><p class="plan-notice">${[!i.copy&&"Add copy or a delivery brief",!safe(i.asset)&&"link the activity assets",!i.approvedA&&"record BRUT review",!i.approvedB&&"record FAUX review"].filter(Boolean).join(" · ")||"Creative and review notes recorded. Confirm dependencies and channel access before launch."}</p><p><b>Depends on:</b> ${esc(i.dependency)}. <b>Budget basis:</b> ${esc(i.basis)}</p>${g?`<div class="plan-guide"><p><b>Role in distribution:</b> ${esc(g.purpose)}</p><p><b>Required assets:</b> ${esc(g.assets)}</p><p><b>How we assess it:</b> ${esc(g.measures)}</p><p><b>Before booking:</b> ${esc(g.prerequisites)} Confirm current access and formats with the channel.</p></div>`:''}
 <div class="plan-fields"><label>Owner<input data-item="owner" value="${esc(i.owner)}"></label><label>Timing / flight dates<input data-item="timing" value="${esc(i.timing)}"></label><label>Delivery status<select data-item="status">${statuses.map(s=>`<option ${i.status===s?'selected':''}>${s}</option>`).join('')}</select></label><label>Unit price (USD)<input type="number" min="0" step="0.01" data-item="price" value="${i.price}"></label><label>Quantity · ${esc(i.unit)}<input type="number" min="0" step="0.01" data-item="quantity" value="${i.quantity}"></label><label>BRUT contribution (%)<input type="number" min="0" max="100" data-item="share" value="${i.share}"></label></div><p>FAUX funds the remaining ${100-i.share}%. Selected activity: <b>${money(cost(i))}</b> before contingency. In-kind work is described separately from cash.</p>
 <label>Channel copy / script / deliverable brief<textarea rows="5" data-item="copy" placeholder="Add headlines, body copy, CTA, script, or the delivery brief for this activity.">${esc(i.copy)}</textarea></label><label>Destination URL<input type="url" data-item="destination" value="${esc(i.destination)}" placeholder="https://…"></label>${link(i.destination,'Open destination')}
 <label>Activity assets URL<input type="url" data-item="asset" value="${esc(i.asset)}" placeholder="Link a shared folder, design file or approved asset"></label>${link(i.asset,'Open activity assets')}
 <div class="plan-brand-links">${link(plan.assetsA,'BRUT brand assets')}${link(plan.assetsB,'FAUX brand assets')}</div><label>Usage rights, versions and delivery notes<textarea rows="2" data-item="rights" placeholder="Specify asset version, allowed channels, usage term and restrictions.">${esc(i.rights)}</textarea></label>
 <div class="plan-checks"><label><input type="checkbox" data-item="approvedA" ${i.approvedA?'checked':''}> BRUT review recorded</label><label><input type="checkbox" data-item="approvedB" ${i.approvedB?'checked':''}> FAUX review recorded</label></div><p class="plan-note">Review markers are local planning notes, not authenticated approvals. Changing copy, assets, destination or rights resets both markers.</p></section>`}
function render(){const t=totals(),selected=plan.items.filter(i=>i.included),role=document.getElementById('roleSelect')?.value||'admin';for(const root of roots){root.innerHTML=`<div class="plan-heading"><div><p class="section-label">BRUT × FAUX · shared delivery plan</p><h2>What we’re making. How it reaches people.</h2><p>Agree the idea, fund the work, and open an activity to see its copy and assets.</p></div><button class="button secondary" type="button" data-plan-export>Export plan CSV</button></div><p class="plan-notice">Starting template: the uploaded hotel × fashion planning kit, dated September 19, 2026. Prices are proposed allowances, not agreed BRUT × FAUX commitments. Replace example scope and confirm quotes before launch.</p><p class="plan-save" role="status">${esc(message)}</p>
 <div class="plan-totals"><div><span>Total proposed cash</span><strong>${money(t.total)}</strong><small>Includes ${money(t.reserve)} contingency</small></div><div><span>${role==='brut'?'Your contribution · ':''}BRUT</span><strong>${money(t.a)}</strong><small>Per-activity share + reserve</small></div><div><span>${role==='faux'?'Your contribution · ':''}FAUX</span><strong>${money(t.b)}</strong><small>Remaining share + reserve</small></div><div><span>Selected activities</span><strong>${selected.length} / ${plan.items.length}</strong><small>Optional work is excluded</small></div></div>
 <nav class="plan-tabs" aria-label="Planning views">${[['concept','Agreed idea'],['activities','Activities & creative'],['budget','Budget by channel']].map(([id,label])=>`<button type="button" data-plan-view="${id}" aria-pressed="${view===id}">${label}</button>`).join('')}</nav>
 ${view==='concept'?`<section class="plan-detail"><h3>Make the customer benefit clear first.</h3><label>Co-branded product or experience<textarea rows="3" data-plan="concept">${esc(plan.concept)}</textarea></label><label>Why customers will want it<textarea rows="3" data-plan="benefit">${esc(plan.benefit)}</textarea></label><div class="plan-checks"><label><input type="checkbox" data-plan="approvedA" ${plan.approvedA?'checked':''}> BRUT concept decision recorded</label><label><input type="checkbox" data-plan="approvedB" ${plan.approvedB?'checked':''}> FAUX concept decision recorded</label></div><p>${plan.approvedA&&plan.approvedB?'Both concept decisions are recorded. Review the funded plan and production prerequisites next.':'Concept alignment is pending. You can draft activities now; confirm both decisions before production.'}</p><label>BRUT brand asset library<input type="url" data-plan="assetsA" value="${esc(plan.assetsA)}" placeholder="https://…"></label>${link(plan.assetsA,'Open BRUT library')}<label>FAUX brand asset library<input type="url" data-plan="assetsB" value="${esc(plan.assetsB)}" placeholder="https://…"></label>${link(plan.assetsB,'Open FAUX library')}<p class="plan-note">Brand libraries appear in every activity. Add links with the correct access permissions; this prototype does not upload or grant access to files.</p></section>`:''}
 ${view==='activities'?`<div class="plan-concept"><strong>${esc(plan.concept)}</strong><p>${esc(plan.benefit)}</p><small>${plan.approvedA&&plan.approvedB?'Concept decisions recorded locally':'Concept decisions pending · draft planning'}</small></div><div class="plan-filters"><label>Stage<select data-plan-stage><option value="all">All stages</option>${[...new Set(plan.items.map(i=>i.stage))].map(s=>`<option ${stage===s?'selected':''}>${s}</option>`).join('')}</select></label><label>Show<select data-plan-filter>${[['selected','Selected activities'],['optional','Optional activities'],['all','All activities']].map(([s,n])=>`<option value="${s}" ${filter===s?'selected':''}>${n}</option>`).join('')}</select></label></div><div class="plan-workspace"><div class="plan-list">${plan.items.filter(i=>(stage==='all'||i.stage===stage)&&(filter==='all'||(filter==='selected'?i.included:!i.included))).map(i=>`<article class="plan-list-row ${active===i.id?'active':''}"><label class="plan-include"><input type="checkbox" data-include="${i.id}" ${i.included?'checked':''}><span class="sr-only">Include ${esc(i.title)}</span></label><button type="button" data-plan-activity="${i.id}" aria-pressed="${active===i.id}"><small>${i.id} · ${esc(i.timing)}</small><strong>${esc(i.title)}</strong><span>${esc(i.owner)} · ${esc(i.status)}</span><span>${money(cost(i))}${!i.included?' · optional':''}</span></button></article>`).join('')||'<p>No activities match this filter.</p>'}</div>${detail()}</div>`:''}
 ${view==='budget'?`<div class="plan-budget-controls"><label>External-cost contingency (%)<input type="number" min="0" max="100" step="0.1" data-plan="reserve" value="${plan.reserve}"></label><p>Reserve applies to external cash costs only. Agency fees and in-kind brand contributions are excluded. Each reserve follows that activity’s funding split.</p></div><div class="plan-categories">${Object.entries(t.categories).map(([c,n])=>`<div><span>${esc(c)}</span><strong>${money(n)}</strong></div>`).join('')}<div><span>External-cost reserve</span><strong>${money(t.reserve)}</strong></div></div><div class="plan-table-wrap"><table><caption>Selected activities · USD before contingency</caption><thead><tr><th>Activity / channel</th><th>Cost type</th><th>Total</th><th>BRUT</th><th>FAUX</th></tr></thead><tbody>${selected.map(i=>`<tr><td><button type="button" data-plan-activity="${i.id}">${esc(i.title)} ↗</button></td><td>${esc(i.category)}</td><td>${money(cost(i))}</td><td>${money(cost(i)*i.share/100)}</td><td>${money(cost(i)*(1-i.share/100))}</td></tr>`).join('')}</tbody></table></div><p class="plan-note">Agency fees are selling prices, not agency profit. Cash excludes internal time, tax, discounts, royalties and revenue shares unless added to scope. Paid media does not guarantee reach; outreach does not guarantee editorial placement. Review management scope if selecting more than three ad platforms.</p>`:''}
 <div class="plan-next"><strong>After launch: compare delivery with outcomes.</strong><p>Use the 30-, 60- and 90-day report to assess visits, audience response and commercial outcomes for each partner.</p><a href="${role==='admin'?'/reports':'/portal/'+role+'/results'}">Open outcome reports ↗</a></div>`}}
function exportPlan(){const t=totals();const head=['id','stage','activity','selected','timing','owner','dependency','deliverables','category','unit_price_USD','quantity','cash_USD','BRUT_percent','BRUT_cash_USD','FAUX_cash_USD','external_reserve_USD','status','copy','destination','activity_assets','rights','BRUT_review','FAUX_review','concept','customer_benefit','BRUT_asset_library','FAUX_asset_library'];const rows=plan.items.map(i=>[i.id,i.stage,i.title,i.included?'Yes':'No',i.timing,i.owner,i.dependency,i.deliverables,i.category,i.price,i.quantity,cost(i),i.share,cost(i)*i.share/100,cost(i)*(1-i.share/100),external(i)?cost(i)*plan.reserve/100:0,i.status,i.copy,i.destination,i.asset,i.rights,i.approvedA,i.approvedB,plan.concept,plan.benefit,plan.assetsA,plan.assetsB]);const csv=[head,...rows].map(r=>r.map(v=>'"'+String(v??'').replace(/^[=+@\-\t\r]/,"'$&").replaceAll('"','""')+'"').join(',')).join('\r\n');const url=URL.createObjectURL(new Blob(['\uFEFF'+csv],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='the-pull-partnership-plan.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
for(const root of roots){root.addEventListener('click',e=>{const b=e.target.closest('[data-plan-view]'),a=e.target.closest('[data-plan-activity]');if(b){view=b.dataset.planView;render()}if(a){active=a.dataset.planActivity;view='activities';render();root.querySelector('.plan-detail')?.scrollIntoView({block:'nearest',behavior:'smooth'})}if(e.target.closest('[data-plan-export]'))exportPlan()});root.addEventListener('change',e=>{const t=e.target;if(t.matches('[data-plan-stage]')){stage=t.value;render();return}if(t.matches('[data-plan-filter]')){filter=t.value;render();return}if(!t.matches('input,textarea,select'))return;if(!t.checkValidity()){t.reportValidity();return}if(t.dataset.include){plan.items.find(i=>i.id===t.dataset.include).included=t.checked}else if(t.dataset.item){const i=plan.items.find(i=>i.id===active),k=t.dataset.item;i[k]=t.type==='checkbox'?t.checked:t.type==='number'?Number(t.value):t.value;if(['copy','asset','destination','rights'].includes(k)){i.approvedA=false;i.approvedB=false}}else if(t.dataset.plan){const k=t.dataset.plan;plan[k]=t.type==='checkbox'?t.checked:t.type==='number'?Number(t.value):t.value;if(['concept','benefit'].includes(k)){plan.approvedA=false;plan.approvedB=false}}else return;save();render()})}
document.getElementById('roleSelect')?.addEventListener('change',render);document.getElementById('mobileRoleSelect')?.addEventListener('change',render);window.addEventListener('popstate',render);document.addEventListener('click',e=>{if(e.target.closest('[data-client-screen],[data-primary]'))queueMicrotask(render)});render();
})();
