"""Rebuild the static public marketing pages and their shared navigation."""
from pathlib import Path
import re
ROOT=Path(__file__).resolve().parent.parent
NAV=[('Home','/'),('Services','/services/'),('Approach','/approach/'),('Contact','/contact/')]
def header(current):
    links=''.join(f'<a href="{url}"'+(' aria-current="page"' if current==url else '')+f'>{label}</a>' for label,url in NAV)
    return f'''<a class="pull-skip" href="#main-content">Skip to content</a><header class="m-header"><a class="m-logo" href="/" aria-label="The Pull home">the <i>pull.</i></a><nav class="m-nav" id="marketing-navigation" aria-label="Main navigation">{links}</nav><div class="m-tools" data-theme-host><a class="m-workspace" href="/app/discover">Workspace ↗</a></div><button class="m-menu-toggle" type="button" aria-expanded="false" aria-controls="marketing-navigation">Menu</button></header>'''
FOOTER='''<footer class="m-footer"><div class="m-footer-top"><div class="m-footer-brand"><a class="m-brand" href="/" aria-label="The Pull home">the <i>pull.</i></a><p class="m-brand-note">Your one-stop collaboration shop.</p></div><div><h2>The Pull</h2><nav aria-label="Company"><a href="/services/">Services</a><a href="/approach/">Our approach</a><a href="/contact/">Contact</a></nav></div><div><h2>Explore</h2><nav aria-label="Resources"><a href="/observatory">Observatory ↗</a><a href="/app/discover">Partner Studio ↗</a><a href="/app/support">Support</a></nav></div><div><h2>The details</h2><nav aria-label="Policies"><a href="/privacy/">Privacy</a><a href="/terms/">Terms of use</a><a href="/cookies/">Cookies</a><a href="/accessibility/">Accessibility</a><a href="/editorial-policy/">Editorial &amp; rights</a><button type="button" data-cookie-settings>Cookie settings</button></nav></div></div><div class="m-footer-bottom"><p>© 2026 The Pull.</p><p>Independent brand collaboration services. Third-party brands featured in our research are not presented as clients or endorsements.</p></div></footer>'''
def button(label,url,secondary=False):
    return f'<a class="m-button'+(' secondary' if secondary else '')+f'" href="{url}">{label}<span aria-hidden="true">↗</span></a>'
def cta():
    return '<section class="m-cta"><h2>Good things happen<br>when brands meet.</h2>'+button('Start a conversation','/contact/')+'</section>'
def page(path,title,desc,content):
    dest=ROOT/('index.html' if path=='/' else path.strip('/')+'/index.html');dest.parent.mkdir(parents=True,exist_ok=True)
    dest.write_text(f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{title} — The Pull</title><meta name="description" content="{desc}"><link rel="canonical" href="https://thepullpartnerships.netlify.app{path}"><link rel="icon" href="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 32 32'%3E%3Crect width='32' height='32' rx='8' fill='%23161616'/%3E%3Ctext x='10' y='23' font-size='25' fill='white' font-family='Georgia'%3Ep%3C/text%3E%3C/svg%3E"><link rel="stylesheet" href="/site.css"><link rel="stylesheet" href="/site-shell.css"><link rel="stylesheet" href="/site-dark.css"><link rel="stylesheet" href="/marketing.css"><script src="/site-shell.js"></script><script src="/site-consent.js" defer></script><script src="/marketing.js" defer></script><script type="text/plain" data-pull-feedback data-src="https://www.bugherd.com/sidebarv2.js?apikey=a3ihvj1feiamwnfghbpgeg"></script></head><body class="pull-public marketing">{header(path)}<main id="main-content" tabindex="-1">{content}</main>{FOOTER}</body></html>''')
page('/','Your one-stop collaboration shop','We bring brands together and handle the collaboration. Partner discovery, strategy, creative development, delivery and measurement.',f'''
<section class="m-hero"><img src="/assets/the-pull-together.webp" width="1536" height="1024" alt="Two people in contrasting black and ivory tailoring walk together through a concrete passage." fetchpriority="high"><div><p class="m-kicker">Your one-stop collaboration shop</p><h1>Different worlds.<br>Stronger together.</h1><p>We bring brands together. And handle everything it takes to make the collaboration happen.</p>{button('Discover The Pull','/services/')}</div><p class="m-hero-note">The art of coming together</p></section>
<section class="m-section m-intro"><p class="m-kicker">More than an introduction</p><div><h2>The right partner.<br>The idea. The entire thing.</h2><p class="m-copy">A great collaboration takes more than two names on a product. It takes a shared ambition, a reason for people to care, and someone to bring all the moving parts together.</p><p class="m-copy">That’s where we come in. From the first conversation to the final report, The Pull handles the work around the partnership.</p><a class="m-text-link" href="/approach/">How we make it happen ↗</a></div></section>
<section class="m-section m-rule" id="services"><div class="m-label-row"><p class="m-kicker">From possibility to partnership</p><a class="m-text-link" href="/services/">Explore our services ↗</a></div><div class="m-service-grid"><article class="m-service-card"><span class="m-number">01 / Find the fit</span><h3>A shared reason<br>to do something.</h3><p>Strategy, research, partner discovery, and outreach. We find the connection that makes sense for both brands.</p></article><article class="m-service-card"><span class="m-number">02 / Shape the idea</span><h3>Something neither<br>could make alone.</h3><p>Concept, creative direction, commercial alignment, and a clear proposition both teams can get behind.</p></article><article class="m-service-card"><span class="m-number">03 / Make it happen</span><h3>All the way<br>into the world.</h3><p>Partner coordination, production, approvals, launch, and measurement. One team keeping the collaboration moving.</p></article></div></section>
<section class="m-duo" id="product"><article><p class="m-kicker">The intelligence behind the service</p><h2>Look beyond<br>the announcement.</h2><p>The Observatory explores brand collaborations, the conversation around them, and what the available evidence tells us.</p><a class="m-text-link" href="/observatory">Explore the Observatory ↗</a></article><article><p class="m-kicker">The workspace behind the work</p><h2>One place.<br>A shared direction.</h2><p>Partner Studio is our developing workspace for briefs, decisions, approvals, and results. Explore the proposed client experience.</p><a class="m-text-link" href="/app/discover">Enter the Studio preview ↗</a></article></section>
{cta()}''')
page('/services/','Brand collaboration services','From finding a partner to delivering a launch, The Pull manages brand collaborations through one coordinated engagement.',f'''
<section class="m-page-intro"><p class="m-kicker">What we do</p><h1>The whole<br>collaboration.</h1><p class="m-lede">One coordinated engagement. From the partner you haven’t met yet to the thing you’ll make together.</p></section>
<div class="m-steps"><section class="m-step"><span class="m-number">01</span><h2>Strategy &amp;<br>partner discovery</h2><div><p>Start with what you want the collaboration to achieve. We define the opportunity, explore the audience, and build a shortlist with a clear reason for each match.</p><ul><li>Objectives, audience, and opportunity mapping</li><li>Partner research, evaluation, and prioritisation</li><li>Outreach and the proposition for a first conversation</li></ul></div></section><section class="m-step"><span class="m-number">02</span><h2>Concept &amp;<br>creative direction</h2><div><p>Turn shared potential into a specific idea. A product, experience, campaign, or cultural moment with value for the people it’s meant to reach.</p><ul><li>Collaboration proposition and creative concept</li><li>Audience experience and campaign direction</li><li>Scope, deliverables, and a workable creative brief</li></ul></div></section><section class="m-step"><span class="m-number">03</span><h2>Partner alignment<br>&amp; planning</h2><div><p>Get the important decisions out in the open. We bring the teams around a shared plan and coordinate specialist support where the project needs it.</p><ul><li>Roles, budgets, milestones, and approvals</li><li>Commercial discussions and partner coordination</li><li>Rights and contract coordination with relevant legal advisers</li></ul></div></section><section class="m-step"><span class="m-number">04</span><h2>Production<br>&amp; launch</h2><div><p>Make the plan real. We coordinate the people, suppliers, assets, and decisions needed to bring the collaboration into the world.</p><ul><li>Creative and production coordination</li><li>Partner approvals and launch readiness</li><li>Production schedules, asset handover, and launch coordination</li></ul></div></section><section class="m-step"><span class="m-number">05</span><h2>Marketing<br>&amp; promotion</h2><div><p>Put the collaboration in front of the people it was made for. We plan and run paid, owned, and earned campaigns around your audience, budget, and goals—from building anticipation to sustaining interest after launch.</p><ul><li>Paid advertising across Google Ads, Meta, and ChatGPT</li><li>Newsletter sponsorships and paid placements</li><li>Social posts and coordinated partner content</li><li>Press outreach and media relations</li><li>Media planning, campaign creative, and ongoing optimisation</li></ul></div></section><section class="m-step"><span class="m-number">06</span><h2>Measurement<br>&amp; what comes next</h2><div><p>Understand what happened against the goals set at the start. We connect the available evidence to a useful perspective on performance.</p><ul><li>Reporting against agreed measures</li><li>Coverage, audience response, and channel analysis</li><li>Lessons and recommendations for the next collaboration</li></ul></div></section></div>
<section class="m-section m-rule m-editorial-grid"><div><p class="m-kicker">Meet us where you are</p><h2>Already have a partner?<br>Let’s get to work.</h2></div><div><p>We can start with an ambition, an existing relationship, or an idea that needs a delivery team. The engagement is built around the stage you’re at and the support you need.</p><p class="m-muted">We work alongside brand teams, founders, agencies, and specialist advisers. Scope, fees, external costs, and responsibilities are agreed before work begins.</p>{button('Tell us what you need','/contact/')}</div></section>{cta()}''')
page('/approach/','Our approach','How The Pull turns shared ambition into a collaboration, with clear decisions, coordinated delivery and evidence-led measurement.',f'''
<section class="m-page-intro"><p class="m-kicker">How we work</p><h1>Find the chemistry.<br>Do the work.</h1><p class="m-lede">Good partnerships need both. We combine a strong point of view on the opportunity with the coordination it takes to deliver it.</p></section>
<section class="m-photo"><img src="/assets/the-pull-together.webp" alt="Two contrasting perspectives, moving in the same direction." width="1536" height="1024"><div><p class="m-kicker">One shared ambition</p><h2>Different strengths.<br>A common direction.</h2><p>The question is never just “who could we work with?” It’s “what could we create together that matters?”</p></div></section>
<section class="m-section m-intro"><p class="m-kicker">A clear path together</p><div><h2>Less passing the brief.<br>More moving it forward.</h2><p class="m-copy">We stay connected to the work from strategy through delivery. Both brands know what’s being decided, who owns the next step, and what success is meant to look like.</p></div></section>
<div class="m-steps"><section class="m-step"><span class="m-number">01</span><h2>Start with the ambition.</h2><div><p>We listen to the business goal, the audience, the brand, and the constraints. Together, we define what would make this collaboration worthwhile.</p></div></section><section class="m-step"><span class="m-number">02</span><h2>Build a case for both sides.</h2><div><p>Every partner needs a reason to participate. We connect audience insight, brand fit, and a distinctive idea to a proposition both teams can support.</p></div></section><section class="m-step"><span class="m-number">03</span><h2>Give the work a structure.</h2><div><p>Agree the scope, responsibilities, costs, and decision points. Then bring the right creative, legal, production, and channel specialists around the project.</p></div></section><section class="m-step"><span class="m-number">04</span><h2>Deliver. Learn. Build on it.</h2><div><p>Coordinate the launch and review the evidence. We distinguish attention from outcomes, acknowledge what the data can’t tell us, and identify what to carry forward.</p></div></section></div>
<section class="m-section m-rule" id="questions"><div class="m-faq"><p class="m-kicker">A few things worth knowing</p><h2>Before we meet.</h2><details><summary>Do you handle the actual collaboration?</summary><p>Yes. The service is the collaboration itself: partner discovery, concept development, partner alignment, coordination through launch, and reporting. Deliverables and specialist support are agreed for each engagement.</p></details><details><summary>Can we bring you an existing idea or partner?</summary><p>Absolutely. We can help develop the proposition, bring the teams into alignment, and build the delivery and measurement plan around an existing relationship.</p></details><details><summary>How do you price an engagement?</summary><p>We scope around your goal, the stage of the partnership, and what you need us to deliver. Fees, third-party costs, milestones, and terms are agreed before paid work begins.</p></details><details><summary>What are the Observatory and Partner Studio?</summary><p>The <a href="/observatory">Observatory</a> is our curated collaboration research. <a href="/app/discover">Partner Studio</a> is an interactive preview of our proposed workflow. Studio examples are illustrative; the public preview is not a secure client portal. Research additions save in your browser, and automated monitoring and shared accounts are not connected.</p></details><details><summary>Do you work alongside our existing agency?</summary><p>Yes. We can join an existing team, with a defined collaboration remit and clear responsibilities alongside your agency and specialist advisers.</p></details></div></section>{cta()}''')
page('/contact/','Contact','Tell The Pull about your brand, your idea, or a collaboration you want to make happen.', '''
<section class="m-page-intro"><p class="m-kicker">Let’s talk</p><h1>What could we<br>make happen?</h1><p class="m-lede">A brand you’d love to work with. An idea you can’t shake. Or just a goal that needs a fresh approach. Start there.</p></section>
<div class="m-contact"><div class="m-contact-info"><section><p class="m-kicker">New collaborations &amp; general enquiries</p><a class="m-email" href="mailto:support@the---pull.com?subject=Collaboration%20enquiry">support@the---pull.com ↗</a></section><section><h2>A few useful starting points.</h2><p class="m-muted">Tell us about your brand, what you want to achieve, and whether you already have a partner in mind. A rough timeline is helpful. A polished brief is optional.</p></section><section><p class="m-kicker">Already exploring the workspace?</p><p>Find practical help and report an issue on our <a href="/app/support">support page</a>.</p></section></div>
<form class="m-contact-form" id="enquiry-form"><div class="m-field-row"><label>Your name <span aria-hidden="true">*</span><input name="name" autocomplete="name" required maxlength="100"></label><label>Email <span aria-hidden="true">*</span><input name="email" type="email" autocomplete="email" required maxlength="180"></label></div><label>Brand / company<input name="company" autocomplete="organization" maxlength="150"></label><label>Where are you starting?<select name="stage"><option value="Exploring a new collaboration">Exploring a new collaboration</option><option value="I have a partner in mind">I have a partner in mind</option><option value="I have a concept to develop">I have a concept to develop</option><option value="I need help with delivery">I need help with delivery</option><option value="Agency or specialist partnership">Agency or specialist partnership</option><option value="Something else">Something else</option></select></label><label>What do you have in mind? <span aria-hidden="true">*</span><textarea name="message" required maxlength="3000" placeholder="Your ambition, audience, timing — whatever you know so far."></textarea></label><p class="m-small">* Required. This form prepares an email draft for you to review and send in your email app. It does not submit an enquiry or save these details on this website. Please don’t include confidential information. <a href="/privacy/">Privacy notice</a>.</p><div class="m-actions"><button class="m-button" type="submit">Prepare enquiry <span aria-hidden="true">↗</span></button></div><noscript><p>Email us directly at <a href="mailto:support@the---pull.com">support@the---pull.com</a>. The draft builder needs JavaScript.</p></noscript><section class="m-enquiry-preview" id="enquiry-preview" hidden><h2 style="font-size:28px">Your enquiry is ready.</h2><p class="m-small">Review your draft below, then open your email app to send it. Nothing has been sent yet.</p><label>Email draft<textarea id="enquiry-draft" readonly></textarea></label><div class="m-actions"><a class="m-button" id="enquiry-email" href="mailto:support@the---pull.com">Open email draft ↗</a><button type="button" class="m-button secondary" id="enquiry-copy">Copy enquiry</button></div><p class="m-small">No email app? Copy the enquiry and send it to support@the---pull.com from your usual email service.</p></section><p class="m-status" id="enquiry-status" role="status" aria-live="polite"></p></form></div>''')
# Give existing policy and 404 pages the same public navigation without changing their content.
for file in ['404.html','privacy/index.html','terms/index.html','cookies/index.html','accessibility/index.html','editorial-policy/index.html']:
    p=ROOT/file;s=p.read_text()
    s=s.replace('class="pull-public"','class="pull-public marketing"')
    if '/marketing.css' not in s:s=s.replace('</head>','<link rel="stylesheet" href="/marketing.css"><script src="/marketing.js" defer></script></head>')
    s=re.sub(r'<a class="pull-skip".*?</header>',header(''),s,count=1,flags=re.S)
    s=re.sub(r'<footer\b.*?</footer>',FOOTER,s,count=1,flags=re.S)
    p.write_text(s)
print('Built four marketing pages; updated policy and 404 navigation.')
